### ISSUE TITLE
After recording full screen and saved as .mp4, the .mp4 file can not be played.

### ISSUE THREAD

**Issue by zhtengw** [manateelazycat/deepin-recorder#1]
After recording full screen and saved as .mp4, the .mp4 file can not be played. If I record a rectangle selection of screen, there is no problem.

**Comment by manateelazycat** [comment]
This issue have fixed by patch https://github.com/manateelazycat/deepin-recorder/commit/0ae32f556712d6b1809245bac2a4b3625ef82430

Thanks for report!
